# https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions
# https://grafana.com/blog/2021/03/23/how-i-fell-in-love-with-logs-thanks-to-grafana-loki/
---
- name: Install apt-key
  ansible.builtin.apt_key:
    url: https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
    state: present

- name: Add syslog-ng-ose repo
  ansible.builtin.apt_repository:
    repo: deb https://ose-repo.syslog-ng.com/apt/ stable ubuntu-focal
    state: present
    filename: syslog-ng-ose

- name: install syslog-ng
  apt: 
    name: syslog-ng-core
    state: present
    update_cache: yes

- name: "applying configuration"
  template:
    src="syslog-ng.conf"
    dest="/etc/syslog-ng/syslog-ng.conf"
    owner="root"
    group="root"
    #validate='syslog-ng --syntax-only --cfgfile %s'
  notify:
  - reload syslog-ng
